name: birthday_reminder
description: A Flutter app to remember birthdays.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  flutter_local_notifications: ^19.3.0
  intl: ^0.20.2

flutter:
  uses-material-design: true